modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/596wjr/FangSu_MTR_Addon/issues"
license = "MIT"

[[mods]]
modId = "fangsu"
version = "${version}"
displayName = "FangSu MTR Addon"
authors = "596wjr"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.fangsu]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fangsu]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fangsu]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fangsu]]
modId = "mtr"
mandatory = true
versionRange = "[3.2.2,4.0.0)"
side = "BOTH"

[[dependencies.fangsu]]
modId = "mtrsteamloco"
mandatory = true
versionRange = "[0.5.2,)"
side = "BOTH"