modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/596wjr/FangSu_MTR_Addon/issues"
license = "MIT"

[[mods]]
modId = "fangsu"
version = "${version}"
displayName = "FangSu MTR Addon"
authors = "596wjr"
description = '''
Added blocks such as OBJ-format ticket gates, and provided a set of interfaces to simplify the creation of MTR extensions.
'''
logoFile = "icon.png"

[[dependencies.fangsu]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fangsu]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fangsu]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fangsu]]
modId = "mtr"
mandatory = true
versionRange = "[,4.0.0)"
side = "BOTH"
ordering = "AFTER"

#[[dependencies.fangsu]]
#modId = "mtrsteamloco"
#mandatory = true
#versionRange = "[0.5.2,)"
#side = "BOTH"