blank_issues_enabled: false
contact_links: 
  - name: New feature suggestion 新功能许愿池
    url: https://github.com/596wjr/FangSu_MTR_Addon/discussions/categories/ideas-%E5%BB%BA%E8%AE%AE
    about: Please go to Discussions 请前往Discussions
